.TH SIMPLE SHELL

.SH NAME
simple_shell \- a simple shell program

.SH SYNOPSIS
.B simple_shell as a UNIX command interpreter.

.SH DESCRIPTION
\fBsimple_shell\fR is a minimalistic shell program developed as part of the Holberton School curriculum.
It provides a basic command-line interface for users to interact with the system.

.PP
Users can execute commands, including built-in commands and external programs. 
The shell supports input/output redirection, piping, and basic error handling.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display help message and exit.

.SH COMMANDS
The following are examples of commands supported by \fBsimple_shell\fR:

.TP
.BR echo " STRING"
Display a line of text.

.TP
.BR ls " [OPTION]... [FILE]..."
List directory contents.

.TP
.BR cd " [DIRECTORY]"
Change the shell working directory.

.TP
.BR exit " [STATUS]"
Exit the shell with the specified status code.

.PP
For a complete list of built-in commands and additional features, refer to the online documentation.

.SH EXAMPLES
.B simple_shell -h
Display the help message.

.B simple_shell echo "Hello, World!"
Execute the echo command.

.B simple_shell ls -l
List directory contents in long format.

.B simple_shell cd /path/to/directory
Change the current working directory.

.SH SEE ALSO
Online documentation available at https://github.com/sachihiroo/holbertonschool-simple_shell

.SH AUTHOR
Written by Holberton School students: Saif Chaari and Amina Hwess.

.SH BUGS
Report bugs to https://github.com/sachihiroo/holbertonschool-simple_shell/issues

.SH COPYRIGHT
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.

.SH DISCLAIMER
This man page is not an official documentation and may not cover all features. 
Refer to the online documentation for the most up-to-date information.

